// File generated by FlutterFire CLI.
// This is a placeholder. Run 'flutterfire configure' to generate actual configuration.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBriU3d0yT4tqICtTndMivx9Bt76hbiVro',
    appId: '1:707614370911:web:cdd612e12eb940e642bfea',
    messagingSenderId: '707614370911',
    projectId: 'futsalpro-uas',
    authDomain: 'futsalpro-uas.firebaseapp.com',
    storageBucket: 'futsalpro-uas.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_kREQzaqlTFoOFo92URPjqQHwK8141Ks',
    appId: '1:707614370911:android:4377587c5e70021f42bfea',
    messagingSenderId: '707614370911',
    projectId: 'futsalpro-uas',
    storageBucket: 'futsalpro-uas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD91dJZaiAjBWAoxN1MP8NbzWn5V2dAyNE',
    appId: '1:707614370911:ios:e621f02f129019a242bfea',
    messagingSenderId: '707614370911',
    projectId: 'futsalpro-uas',
    storageBucket: 'futsalpro-uas.firebasestorage.app',
    iosBundleId: 'com.example.manajemenFutsal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD91dJZaiAjBWAoxN1MP8NbzWn5V2dAyNE',
    appId: '1:707614370911:ios:e621f02f129019a242bfea',
    messagingSenderId: '707614370911',
    projectId: 'futsalpro-uas',
    storageBucket: 'futsalpro-uas.firebasestorage.app',
    iosBundleId: 'com.example.manajemenFutsal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBriU3d0yT4tqICtTndMivx9Bt76hbiVro',
    appId: '1:707614370911:web:24ec0d2f14cc8a0842bfea',
    messagingSenderId: '707614370911',
    projectId: 'futsalpro-uas',
    authDomain: 'futsalpro-uas.firebaseapp.com',
    storageBucket: 'futsalpro-uas.firebasestorage.app',
  );

}